### ISSUE TITLE
Create some Beaker acceptance tests

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/puppet-nodejs#139]
Currently this module is without any acceptance tests. It needs some.

**Comment by nibalizer** [comment]
Any isn't exactly true: https://github.com/puppet-community/puppet-nodejs/blob/master/spec/acceptance/class_spec.rb

**Comment by daenney** [comment]
Until Beaker is not horrible to use I don't think we need to require anything in that regard.

**Comment by liamjbennett** [comment]
@daenney would love to hear your long-from thoughts on how we can improve that situation. Drop me an email.

**Comment by nibalizer** [comment]
Me too @daenney @liamjbennett

**Comment by jyaworski** [comment]
Is this something modulesync has solved?

**Comment by juniorsysadmin** [comment]
> Is this something modulesync has solved?

No, there needs to be some tests created.

**Comment by wyardley** [comment]
There are some tests now. I've added some additional proposed tests in #308, though there is definitely room for a lot more acceptance tests.

**Comment by wyardley** [comment]
Going to close for now since there are some tests. My PR would also configure them to run from Travis.
