### ISSUE TITLE
Running `npm install` in a package dir with no arguments

### ISSUE THREAD

**Issue by ingomueller-net** [voxpupuli/puppet-nodejs#154]
I would like to run `npm install` in a package dir with no arguments in order to install the dependencies of this package. I do not want to deploy the package dir itself with npm. This corresponds to the first form of invocation of npm in [the docs](https://docs.npmjs.com/cli/install). I believe that this is currently not possible, right? I suggest to add this functionality though...

**Comment by juniorsysadmin** [comment]
An empty string as the title for a defined type is not valid, so no, you can't do this with the npm defined type at the moment. This should probably be a new type of its own. Say, `run_npm_install { '/path/to/directory': }`

**Comment by igalic** [comment]
+1

**Comment by serviceman** [comment]
+1

**Comment by igalic** [comment]
@serviceman do you wanna provide a patch?
me and @juniorsysadmin are mostly covered in administration these days :(

**Comment by serviceman** [comment]
wish so, but unfortunately I have few time and zero knowledge of Ruby (and rather few of puppet), so I can't make it!

**Comment by jyaworski** [comment]
What's the status of this?

**Comment by igalic** [comment]
@jyaworski this is still desired and missing

**Comment by NoodlesNZ** [comment]
While it's not ideal, you can run nodejs::npm like this:

```
nodejs::npm { 'App dependencies':
  ensure  => 'present',
  package => undef,
  target  => '/home/example/',
}
```
Which runs "npm install" in that directory

**Comment by igalic** [comment]
is that idempotent, though?

**Comment by juniorsysadmin** [comment]
Functionality added by #300
