### ISSUE TITLE
puppetforge reports old version

### ISSUE THREAD

**Issue by tarjei** [voxpupuli/puppet-nodejs#179]
Hi, if you look at this module at puppetforge, it says that version 0.8.0 is the latest:
https://forge.puppetlabs.com/puppetlabs/nodejs

**Comment by nanliu** [comment]
That's not the puppet-community account, see https://forge.puppetlabs.com/puppet/nodejs

**Comment by tarjei** [comment]
Ok, maybe delete the other one? The project-url points to the same repo.

**Comment by igalic** [comment]
i wish the forge, and pmt / r10k would support redirects, or… other things…

**Comment by igalic** [comment]
i beleve we have this now fixed.
