### ISSUE TITLE
$repo_url_suffix ignores 5.x and 4.x (or others)

### ISSUE THREAD

**Issue by sebastianwahn** [voxpupuli/puppet-nodejs#184]
If the parameter $repo_url_suffix is provided with 5.x or 4.x the module will ignore it and default to 0.10.x this is due the fact, that in the file "manifests/repo/nodesource.pp" the parameter $source_baseurl is hardcoded to "https://rpm.nodesource.com/pub/". On this route only Node versions up to 0.10.x are provided. 

For NodeJs version 5.x the repo ($source_baseurl) should be: "https://rpm.nodesource.com/pub_5.x/" (not just /pub/). 
For NodeJs version 4.x the repo ($source_baseurl) should be: "https://rpm.nodesource.com/pub_4.x/" (also not just /pub/).

**Comment by sebastianwahn** [comment]
I saw that this issue was fixed in #174 but is still not available on https://forge.puppetlabs.com/puppet/nodejs due to #182

**Comment by ColinHebert** [comment]
This can be closed now.
