### ISSUE TITLE
Question: uninstall nodejs entirely

### ISSUE THREAD

**Issue by jeff1evesque** [voxpupuli/puppet-nodejs#210]
I've [installed](https://github.com/jeff1evesque/drupal-demonstration/blob/78091894ae6d96e5ee45c920e6a55d7abf2cc8df/puppet/environment/development/manifests/configure_compilers.pp#L43-L51) nodejs via:

```puppet
...
    class { 'nodejs':
        repo_url_suffix => '5.x',
    }
...
```

But, I'm curious: if I no longer need nodejs after provisioning, and want to remove nodejs entirely, is there an appropriate method to remove it?  For example [willdurand/puppet-nodejs](https://github.com/willdurand/puppet-nodejs/blob/0786a61765bf82d1c306816d01df42a442e77c1b/README.md) has the following implementation:

```puppet
::nodejs::install { 'node-v5.4':
  ensure  => absent,
  version => 'v5.4.1',
}
```

**Comment by igalic** [comment]
from what i gather, it should be enough to amend your definition with:
```puppet
class { 'nodejs':
  nodejs_package_ensure => absent,
  repo_url_suffix       => '5.x',
}
```

…unless you're on gentoo.

**Comment by juniorsysadmin** [comment]
Pretty sure things should work with ```nodejs_package_ensure``` set to ```absent``` and the other ```manage_things``` stuff set to ```false```.
