### ISSUE TITLE
/usr/lib/node_modules/<package> not readable with strict default umask

### ISSUE THREAD

**Issue by dev-zero** [voxpupuli/puppet-nodejs#212]
We have the default umask set to 0027.
After installing a NPM package via the NPM provider (that is, globally), I had to do a `chmod -R a+rX` on `/usr/lib/node_modules` first for the module to be accessible by anyone other than `root`.

**Comment by juniorsysadmin** [comment]
@dev-zero I um am not sure what the bug is. Doesn't the 7 in your mask prevent other users from having rwx on this folder? (npm creates that folder if it doesn't exist)

**Comment by juniorsysadmin** [comment]
Closing, given no response

**Comment by dev-zero** [comment]
sure, its our default umask in the end which causes the permissions on the npm-created folders to be too strict. But shouldn't Puppet (recipes) yield the same result on all distros nevertheless (e.g. a working npm package installation)?
But since Puppet doesn't allow to the define a umask when defining a command in a provider, I guess there isn't much you can do here anyway...
