### ISSUE TITLE
/usr/bin/npm doesn't exist when setting a nodejs::npm::global_config_entry

### ISSUE THREAD

**Issue by dandunckelman** [voxpupuli/puppet-nodejs#214]
On a fresh install of an Ubuntu v14.04 node I come across an issue where Puppet fails to set the **global_config_entry** because **/usr/bin/npm** doesn't exist.

Here's my manifest:

```
class ta_linux::ta_nodejs(                                           
  $npm_packages = {},                                                
) {                                                                  
  validate_hash($npm_packages)                                       

  $npm_package_defaults = {                                          
    'require' => Nodejs::Npm::Global_config_entry['strict-ssl'],     
    'target'  => '/usr/lib',                                         
  }                                                                  

  class { '::nodejs':                                                
    manage_package_repo       => false,                              
    nodejs_dev_package_ensure => present,                            
    npm_package_ensure        => present,                            
  }->                                                                

  nodejs::npm::global_config_entry { 'strict-ssl':                   
    ensure  => present,                                              
    value   => false,                                                
  }                                                                  

  create_resources(nodejs::npm, $npm_packages, $npm_package_defaults)
}
```

When I run my acceptance test for this manifest, it works as expected.

But when I run my acceptance test for another class that loads this **ta_linux::ta_nodejs** class, it results in this error:

```
Error: /bin/sh: /usr/bin/npm: No such file or directory

Error: /Stage[main]/Ta_linux::Ta_nodejs/Nodejs::Npm::Global_config_entry[strict-ssl]/Exec[npm_config present strict-ssl]/returns: change from notrun to 0 failed: /bin/sh: /usr/bin/npm: No such file or directory
```

I have the _require_ relationship between the **nodejs** class and the **global_config_entry** define, but that doesn't enforce the installation of **npm** before trying to set that configuration option.

Obviously, this is pretty obscure and difficult to reproduce (outside of my own environment), but if anyone has any insight here, I'm all ears.

Thanks

**Comment by dandunckelman** [comment]
Not sure that it makes a difference, but I've also had the **nodejs** class like this:
```
class { '::nodejs': }->
```

and had the same results

**Comment by jyaworski** [comment]
AFAIK, you can't have a require relationship on a define.

However, it does seem like we should add an include ::nodejs to that define.

**Comment by rnelson0** [comment]
Maybe split into two subclasses and contain them. Then order the two,
Class[a] -> Class [b]. You could try the spaceship collector but it's
possible a resource in the class will be out orpf order, unless you contain
the whole thing.

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by juniorsysadmin** [comment]
@dandunckelman Is this still an issue with the latest release?

**Comment by dandunckelman** [comment]
@juniorsysadmin yes.  On a 2nd puppet run, it is resolved...so it's not a deal breaker

**Comment by jyaworski** [comment]
Tagging @ghoneycutt as this looks like the problem that https://github.com/voxpupuli/puppet-nodejs/pull/221 was supposed to solve.

**Comment by ghoneycutt** [comment]
You shouldn't need the arrow syntax. The define will include the nodejs class. You are mixing `include ::nodejs` which happens in the define with the parameterized class syntax. Perhaps that is causing you trouble.

**Comment by dandunckelman** [comment]
I've since updated my class to this:
```
class ta_linux::ta_nodejs(
  $npm_packages = {},
) {
  validate_hash($npm_packages)

  $npm_package_defaults = {
    'provider' => 'npm',
    'require'  => Class['nodejs'],
  }

  class { 'nodejs': }

  nodejs::npm::global_config_entry { 'strict-ssl':
    ensure => present,
    value  => false,
  }

  Class['::nodejs'] -> Package <| provider == 'npm' |>

  create_resources(package, $npm_packages, $npm_package_defaults)
}
```

and still receive the error on the first run when the **ta_linux::ta_nodejs** class is loaded by another class like this:
```
class ta_apps::portal_web() {
  # other stuff to install packages, rvm, apache, and other stuff

  class { 'ta_linux::ta_nodejs':
    npm_packages => {
      'forever' => {
        'ensure' => hiera("pkg_ensure_forever"),
      },
    },
  }
}
```

**Comment by juniorsysadmin** [comment]
Can anyone else report that this is still occurring?

**Comment by juniorsysadmin** [comment]
Closing due to no further reports providing confirmation of a bug.
