### ISSUE TITLE
provider broken on Puppet v3.8.6 w/ Ruby 1.8.7

### ISSUE THREAD

**Issue by ghoneycutt** [voxpupuli/puppet-nodejs#217]
```Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/package: Could not autoload puppet/provider/package/npm: /etc/puppet/environments/development/modules/nodejs/lib/puppet/provider/package/npm.rb:3: syntax error, unexpected ':', expecting $end
...package).provide :npm, parent: Puppet::Provider::Package do```

seems this was changed in ce1460cb

**Comment by bastelfreak** [comment]
Hi,

we do not support Ruby1.8.7 anymore. Please take a look at the alternative solutions like the Puppet AIO packages or ruby replacements.

**Comment by ghoneycutt** [comment]
For anyone else running into this, v1.3.0 seems to be the last release that supports ruby 1.8.7.

**Comment by gdubicki** [comment]
Note that this makes it not work on Centos 6.

**Comment by bastelfreak** [comment]
@gdubicki this is not 100% correct, it only fails on CentOS 6 with Puppet 3.X. You can use Puppet 4.X on CentOS 6 as well, this version has a bundled ruby version and that supports this module.

**Comment by gdubicki** [comment]
Thanks for clarification, @bastelfreak !
