### ISSUE TITLE
new release to fix Nodesource 4.x on CentOS 6.7

### ISSUE THREAD

**Issue by NoodlesNZ** [voxpupuli/puppet-nodejs#222]
I'm trying to use nodesource 4.x on CentOS 6.7, which in the version on the forge throws an error. This was fixed in the master branch. Is it possible to get a minor version release so that the fix is available on the forge?

Thanks

**Comment by igalic** [comment]
@NoodlesNZ if you wanna help out, please checkout our release process: https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module

**Comment by bastelfreak** [comment]
I would like to modulesync() before we do a new release:
https://github.com/voxpupuli/puppet-nodejs/pull/223

**Comment by bastelfreak** [comment]
I started the release thing and would like to get some input: https://github.com/voxpupuli/puppet-nodejs/pull/224

**Comment by juniorsysadmin** [comment]
Release has been done

**Comment by bastelfreak** [comment]
as a side note, we had to drop ruby1.8.
