### ISSUE TITLE
Puppet Forge outdated

### ISSUE THREAD

**Issue by mbrodala** [voxpupuli/puppet-nodejs#226]
Every release after 0.8.0 is missing on [Puppet forge](https://forge.puppet.com/puppetlabs/nodejs). Can you have a look here and ensure all newer releases are available?

**Comment by alexjfisher** [comment]
@mbrodala Voxpupuli took over this module.  Try https://forge.puppet.com/puppet/nodejs

**Comment by alexjfisher** [comment]
I think https://forge.puppet.com/puppetlabs/nodejs should have had a final release documenting the module's migration.  @bastelfreak ?

**Comment by mbrodala** [comment]
@alexjfisher Ah thanks a lot. I indeed couldn't see that from Forge. (Although I found it odd that a puppetlabs module does not live on https://github.com/puppetlabs ;-) )

**Comment by alexjfisher** [comment]
As well as this issue, there was also https://github.com/voxpupuli/puppet-nodejs/issues/179 nearly 6 months ago.

@hunner Are you able to expedite https://tickets.puppetlabs.com/browse/MODULES-2491?
