### ISSUE TITLE
No support for Xenial with NodeJS6

### ISSUE THREAD

**Issue by ColinHebert** [voxpupuli/puppet-nodejs#228]
Currently attempting to install node6.x with Ubuntu Xenial fails with

> Error: Evaluation Error: Error while evaluating a Function Call, Var $repo_url_suffix with value '6.x' is not set correctly for Ubuntu 16.04. See README. at /etc/puppetlabs/code/environments/production/modules/nodejs/manifests/init.pp:48:9 on node ....

It might be worth making the check less restrictive for newer versions/platforms

**Comment by bastelfreak** [comment]
hi @ColinHebert, thanks for finding that bug. Are you able to also provide a PR with a fix?

**Comment by ColinHebert** [comment]
Sure, dealt with in #229

**Comment by bastelfreak** [comment]
merged
