### ISSUE TITLE
npm provider fail (module not working) on CentOS6

### ISSUE THREAD

**Issue by fnerdwq** [voxpupuli/puppet-nodejs#235]
On a CentOS 6 system (ruby 1.8.7!) the npm provider with the new syntax in your module version 2 does not work anymore. I get the following error
```
Error: Could not autoload puppet/provider/package/npm: /root/nodejs/lib/puppet/provider/package/npm.rb:3: syntax error, unexpected ':', expecting $end
...package).provide :npm, parent: Puppet::Provider::Package do
                              ^
Error: Could not run: Could not retrieve facts for localhost.fritz.box: Could not autoload puppet/provider/package/npm: /root/nodejs/lib/puppet/provider/package/npm.rb:3: syntax error, unexpected ':', expecting $end
...package).provide :npm, parent: Puppet::Provider::Package do
```

Thanks for investigating.

**Comment by bastelfreak** [comment]
Hi,
with the 2.X releases of the module we dropped ruby1.8 support. Please use the older releases, or upgrade to centos7 or switch to the new puppet AIO packages. They ship a bundled ruby version which is newer. You can always contact us at #voxpupuli on freenode if you need any help for any of the steps.

**Comment by fnerdwq** [comment]
Hi, unfortunately not that simple. We use puppet 3.8 with foreman on CentOS 6 and 7. And there is the need to install nodejs6.

So I might need to fork 1.3 an patch the installation of the 6.x repo.

Thanks anyway.

**Comment by justinIs** [comment]
Hey I'm still seeing this issue on 2.3.0, which claims to have Puppet 3 support. I'm currently on Puppet v3.8.7, does anyone know if that is bundled with ruby 1.8? Does the puppet-nodejs module support that version of ruby?
