### ISSUE TITLE
Puppet Forge still has 0.8.0 as latest release

### ISSUE THREAD

**Issue by amosshapira** [voxpupuli/puppet-nodejs#237]
Puppet Forge still points to an old release: https://forge.puppet.com/puppetlabs/nodejs

**Comment by bastelfreak** [comment]
HI,

you can find our latest release at https://forge.puppet.com/puppet/nodejs. Sadly puppetlabs didn't make a deprecation release for their old module.

**Comment by alexjfisher** [comment]
@amosshapira The nodejs module was adopted by the Vox Pupuli project. Try https://forge.puppet.com/puppetlabs/nodejs instead.

This is a duplicate of https://github.com/voxpupuli/puppet-nodejs/issues/226 :(

**Comment by amosshapira** [comment]
Thanks. Sorry for repeating an answered question. Perhaps if you can't control the old module add a comment about this in your README file?
