### ISSUE TITLE
incorrect repo validation for Ubuntu 15.04/15.10

### ISSUE THREAD

**Issue by drkp** [voxpupuli/puppet-nodejs#238]
It looks like b8c672d0 changed the validate_re's for 15.04 and 15.10 to have a trailing x, so they'll only match 4.xx not 4.x. This doesn't seem right...

**Comment by bastelfreak** [comment]
Hi @drkp,

thanks for reporting this. Are you able to also provide a patch for it?

**Comment by drkp** [comment]
Sure, just submitted #239

**Comment by juniorsysadmin** [comment]
Fixed by #239
