### ISSUE TITLE
Is node version 6.x support?

### ISSUE THREAD

**Issue by gVien** [voxpupuli/puppet-nodejs#243]
Looking at the `repo_url_suffix` section, I don't see node version 6.x supported. Is there a way to install node version 6.x using this module on CentOS6?

**Comment by juniorsysadmin** [comment]
```repo_url_suffix => '6.x'``` should work according to https://github.com/voxpupuli/puppet-nodejs/blob/master/manifests/init.pp#L62

**Comment by gVien** [comment]
looks like it as the number `6` indicates so. Thanks for pointing that out!
