### ISSUE TITLE
How to select an exact version of node or npm

### ISSUE THREAD

**Issue by LeeGDavis** [voxpupuli/puppet-nodejs#280]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Whatever ships with Vagrant 1.8.6
- Ruby: 
- Distribution: RHEL 7.2.x
- Module version: 2.3.0

## How to reproduce (e.g Puppet code you use)
I'm trying to fix the nodejs install to a particular version.  Using nodejs_package_ensure.
Tried:
- `nodejs_package_ensure => '6.9.4'`
- `nodejs_package_ensure => '6.9.4*'`
- `nodejs_package_ensure => '6.9.4-*'`

I would be happy to be pointed to the particular piece of documentation that outlines this and would appreciate any pointers.  All I could find that seems relevant is:
```
nodejs_package_ensure

When set to present or a version number, determines whether to install the Node.js package. Defaults to present.
```

## What are you seeing
A theme of the following error below reflecting the ensure value above:
```
Error: Could not update: Failed to update to version 6.9.4, got version 6.9.4-1nodesource.el7.centos instead
Error: /Stage[main]/Nodejs::Install/Package[nodejs]/ensure: change from absent to 6.9.4 failed: Could not update: Failed to update to version 6.9.4, got version 6.9.4-1nodesource.el7.centos instead

```

## What behaviour did you expect instead
I expected to be able to select a fixed version major.minor.patch

**Comment by juniorsysadmin** [comment]
Sounds like you're hitting https://tickets.puppetlabs.com/browse/PUP-1244

**Comment by LeeGDavis** [comment]
Thanks @juniorsysadmin looking into this angle now.

**Comment by LeeGDavis** [comment]
@juniorsysadmin yes my tests were using 3.8.4. Puppet 4.x appears to have resolved this issue.  Thanks for the tip!
