### ISSUE TITLE
repo created by puppet

### ISSUE THREAD

**Issue by giammy2290** [voxpupuli/puppet-nodejs#284]
hi,

the nodejs repository added by puppet:

https://deb.nodesource.com/node_v5.x/dists/trusty/main/binary-amd64/Packages

doesn't works (404)

ubuntu 14.04
puppetserver                     2.6.0-1puppetlabs1

**Comment by juniorsysadmin** [comment]
@giammy2290 looks like the url_suffix https://github.com/voxpupuli/puppet-nodejs#repo_url_suffix that you're passing in is not right, no? (Should be ```5.x````)

**Comment by juniorsysadmin** [comment]
@giammy2290 Ping

**Comment by giammy2290** [comment]
Yeps, sorry for the delay, my fault, now works :)

Gianmarco Carrieri
