### ISSUE TITLE
Installation on CentOS 7 fails, can't remove npm package

### ISSUE THREAD

**Issue by Aethylred** [voxpupuli/puppet-nodejs#287]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 2.0.0
- Distribution: CentOS 7
- Module version: 2.3.0

## How to reproduce (e.g Puppet code you use)

Using `puppet-nodejs` and `stahnma-epel`

```
class{'epel':
  before => Class['redis','nodejs','apache','ruby'],
}
class{'nodejs':
  npm_package_ensure => 'present',
  before             => Class['gitlab'],
}
```

## What are you seeing

Puppet run fails as it's trying to remove a package depended on by the nodejs package

## What behaviour did you expect instead

That nodejs would install with dependencies

## Output log

```
Notice: /Stage[main]/Nodejs::Install/Package[nodejs]/ensure: created
Error: Execution of '/bin/rpm -e npm-3.10.10-1.6.9.4.2.el7.x86_64' returned 1: error: Failed dependencies:
        npm = 1:3.10.10-1.6.9.4.2.el7 is needed by (installed) nodejs-1:6.9.4-2.el7.x86_64
Error: /Stage[main]/Nodejs::Install/Package[npm]/ensure: change from 3.10.10-1.6.9.4.2.el7 to absent failed: Execution of '/bin/rpm -e npm-3.10.10-1.6.9.4.2.el7.x86_64' returned 1: error: Failed dependencies:
        npm = 1:3.10.10-1.6.9.4.2.el7 is needed by (installed) nodejs-1:6.9.4-2.el7.x86_64
```

## Any additional information you'd like to impart

Forcing `npm` package to install is a work around:

```
package{$dep_packages:
  ensure => 'present',
  before => Class['gitlab','redis','nodejs'],
}
```

**Comment by wyardley** [comment]
@Aethylred is this still an issue with the most recent version?

**Comment by juniorsysadmin** [comment]
Bump
> @Aethylred is this still an issue with the most recent version?

**Comment by juniorsysadmin** [comment]
No response, closing

**Comment by philomory** [comment]
Sorry to say that this is still a problem. The gist of the issue appears to be that nodejs is getting installed from the nodesource repository, but npm is getting installed from epel. The version of npm in epel relies on the version of nodejs in epel, which is much older that the version in nodesource.

**Comment by alchemyconsulting** [comment]
+1 - I can't work out a workaround either, makes the module unuseable on CentOS7 for me.  Using puppet-epel not stahnma-epel.

**Comment by delinuxspecialist** [comment]
If you use nodejs from Nodesource on CentOS 7 you should set npm_package_ensure => 'absent' because the nodejs package on Nodesource already contains the npm binary. It also states this in the documentation of the module although you might have to read more than the first two lines ;) No TL;DR here.
