### ISSUE TITLE
Centos 6.6 and 7 - Cannot retrieve repository metadata

### ISSUE THREAD

**Issue by dev-dull** [voxpupuli/puppet-nodejs#288]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.4.1
- Ruby: 2.2.5
- Distribution: centos 6.6 and 7
- Module version: 2.0.1 (prod), 2.3.0 (`bundle exec rake beaker`)

## How to reproduce (e.g Puppet code you use)
String $nodejs_version = '7.0.0'
class { '::nodejs':
  repo_url_suffix    => $nodejs_version,
}

## What are you seeing
For Centos 7, the error displays the full URL which I've tested and is valid. The issue here appears that `yum` is looking for the repomd.xml metadata file, but can't find it because it exists in `repodata/` subdirectory on the repository. I realize this likely falls into your, "not my problem" bucket, but I wanted to file a ticket here in case the issue is not as direct as it appears to be (and also in case you have a direct line to the Node team).

## What behaviour did you expect instead
installed 7.0.0 via RPM repo.

## Output log
Centos 6.6 error via beaker:
Notice: /Stage[main]/Nodejs::Repo::Nodesource::Yum/Yumrepo[nodesource-source]/ensure: created
  Info: changing mode of /etc/yum.repos.d/nodesource-source.repo from 600 to 644
  **Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install nodejs' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: nodesource. Please verify its path and try again**
  Error: /Stage[main]/Nodejs::Install/Package[nodejs]/ensure: change from purged to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install nodejs' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: nodesource. Please verify its path and try again

**Comment by dev-dull** [comment]
Closing this issue. The fix here is to use '7.x' where '7.0.0' is currently being used. This had previously been tried, but I fell victim to a poorly timed 500 error from the RPM repo.

**Comment by bastelfreak** [comment]
ah, bad timing :D 
thanks for reporting this!
