### ISSUE TITLE
NPM Proxy

### ISSUE THREAD

**Issue by Poil** [voxpupuli/puppet-nodejs#290]
Hi,

We used internal repository for all OS packages
But for NPM packages we don't mirror it, and we need to set a proxy.
Today it does not seem possible to have no-proxy on "repo" but a proxy on NPM.
We also manage "/root/.npmrc" but it only take _auth into account (no way to add other parameter), perhaps it will be easier to allow a hash that contains keys=>values

Best regards,

**Comment by juniorsysadmin** [comment]
Fixed by #292
