### ISSUE TITLE
Add support for NodeJS 8.x

### ISSUE THREAD

**Issue by andrewwippler** [voxpupuli/puppet-nodejs#323]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: n/a
- Ruby: n/a
- Distribution: n/a
- Module version: 3.1.0

## Output log
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Var $repo_url_suffix with value '8.x' is not set correctly for CentOS 7.3.1611. See README. 

## Any additional information you'd like to impart
Add support for NodeJS 8.x https://github.com/nodejs/Release#release-schedule1

**Comment by juniorsysadmin** [comment]
> Module version: 3.1.0

@andrewwippler I'm pretty sure this is not the behaviour in 3.1.0 since we stopped validating suffixes in #271 Did you mean 2.1.0?

**Comment by andrewwippler** [comment]
Yep, it was me. The module was not updating because r10k needs a `puppet/nodejs` and I was giving it a `puppet-nodejs`
