### ISSUE TITLE
Apt module missing as a dependency

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/puppet-nodejs#332]
the following module is missing as a dependency in this module and should be fixed.

puppetlabs-apt

**Comment by alexjfisher** [comment]
See https://github.com/voxpupuli/puppet-virtualbox/issues/43

**Comment by juniorsysadmin** [comment]
@TraGicCode puppetlabs-apt is a soft dependency: https://puppet.com/docs/puppet/5.3/style_guide.html#dependencies
It is mentioned in the README though: https://github.com/voxpupuli/puppet-nodejs/blob/master/README.md#module-dependencies

**Comment by TraGicCode** [comment]
@juniorsysadmin very strange, my interpretation of a soft dependency was my code doesn’t reference any code from other modules but another modules code is expected to be used to setup certain prequisites. If you want to use that module you can. If not do it your own way.  Is this not the defined informal definition of this?

**Comment by TraGicCode** [comment]
Looked at the puppet docs got me fixed up. Going to update my definition. Thanks guys!
