### ISSUE TITLE
Handling os and family facts issue

### ISSUE THREAD

**Issue by cmseal** [voxpupuli/puppet-nodejs#344]
Hope what I've put below is enough to help.  First time I've raised an issue on GitHub before.  Couldn't find anything to suggest why this doesn't seem to work.  Help greatly appreciated!

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Agent - 3.8.5
- Ruby: 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
- Distribution: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-101-generic x86_64)
- Module version:  4.0.1

## How to reproduce (e.g Puppet code you use)
  class { 'nodejs': }

## What are you seeing
  Error during/after loading facts

## What behaviour did you expect instead
  Accept the OS and family to then install nodejs and npm

## Output log:
  Error: Could not retrieve catalog from remote server: Error 500 on SERVER: {"message":"Server Error: Evaluation Error: A substring operation does not accept a String as a character index. Expected an Integer at /etc/puppetlabs/code/environments/test/modules_3rdparty/nodejs/manifests/params.pp:16:32 on node test_node","issue_kind":"RUNTIME_ERROR"}

**Comment by juniorsysadmin** [comment]
@cmseal Puppet 3 is EOL and is not actively supported in any of our modules. Does the issue still occur with a Puppet4 agent/master?

**Comment by cmseal** [comment]
Yes, I’m afraid it seems to work fine. I’ll have to find another option until we have puppet upgraded.
