### ISSUE TITLE
Wrong repository entry created in Debian stretch

### ISSUE THREAD

**Issue by hessijames79** [voxpupuli/puppet-nodejs#355]
- Puppet: 4.10.9
- Ruby: 2.3.3p222
- Distribution: Debian stretch
- Module version: 4.0.1

## How to reproduce (e.g Puppet code you use)
class { 'nodejs': }

## What are you seeing
# grep deb /etc/apt/sources.list.d/nodesource.list
deb https://deb.nodesource.com/node_0.10 stretch main

apt-get update yields:
Err:4 https://deb.nodesource.com/node_0.10 stretch/main amd64 Packages
  404  Not Found
[...]
W: The repository 'https://deb.nodesource.com/node_0.10 stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://deb.nodesource.com/node_0.10/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

## What behaviour did you expect instead
The official installer from https://deb.nodesource.com/setup maps stretch to jessie. Hence, the correct repository entry for (Debian stretch) is:
deb https://deb.nodesource.com/node_0.10 jessie main

**Comment by bastelfreak** [comment]
Thanks for rising up this issue. Are you able to provide a patch for it?

**Comment by juniorsysadmin** [comment]
Hi @hessijames79 ,
You are right in pointing out that the official installer script maps stretch to jessie, but the stretch folder structure also exists at the apt NodeSource URL.  https://github.com/voxpupuli/puppet-nodejs#repo_url_suffix lists the available versions to expect there.
Note that 0.10 is an ancient Nodejs version that you probably don't want - some time ago it was the minimum supported by most operating systems so was left as the default in this module.
Version 5.0.0 of this module (at the Forge real soon now ) allows one to use the `repo_release` parameter to override repository entry with 'jessie' similar to what you have done above, if you still want 0.10

**Comment by juniorsysadmin** [comment]
8.x is now the default version, which should make things smoother. (See #356)
