### ISSUE TITLE
Ubutnu 16.04 second provisioning fails & puts node.js in invalid state

### ISSUE THREAD

**Issue by MichaelMackus** [voxpupuli/puppet-nodejs#360]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.3
- Ruby: 2.3.1p112 (2016-04-26)
- Distribution: Ubuntu 16.04
- Module version: 5.0.0

## How to reproduce (e.g Puppet code you use)

```class { '::nodejs' }```

## What are you seeing

First provision, everything works fine. Second time I provision the server (no matter what combination of repo_url_suffix or manage_repo settings), I get a circular symlink error. It seems like /usr/bin/node is symlinked to /etc/alternatives/nodejs which is *also* symlinked to /usr/bin/node!

## What behaviour did you expect instead

Idempotent node.js installation, no matter how many times provision is run.

## Output log

```
Notice: /Stage[main]/Nodejs::Install/File[/usr/bin/node]/ensure: ensure changed 'file' to 'link'
Notice: /Stage[main]/Nodejs::Install/File[/usr/share/man/man1/node.1.gz]/ensure: ensure changed 'file' to 'link'
Error: Execution of '/usr/local/bin/npm install --global bower' returned 126: /usr/bin/env: 'node': Too many levels of symbolic links
Error: /Stage[main]/Base::Provision::Nodejs/Package[bower]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/local/bin/npm install --global bower' returned 126: /usr/bin/env: 'node': Too many levels of symbolic links
Error: Execution of '/usr/local/bin/npm install --global yarn' returned 126: /usr/bin/env: 'node': Too many levels of symbolic links
Error: /Stage[main]/Base::Provision::Nodejs/Package[yarn]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/local/bin/npm install --global yarn' returned 126: /usr/bin/env: 'node': Too many levels of symbolic links
```

**Comment by MichaelMackus** [comment]
NOTE: the `yarn` package I'm installing doesn't seem to matter, the relevant lines (that shouldn't be in the output log) are the first 2 lines in the output log above. Node.js is working before this point, and if puppet-nodejs can be stopped from creating the circular symlink this issue will be solved.

**Comment by juniorsysadmin** [comment]
@MichaelMackus We dropped symlink management in #347 , which is in 5.0.0. Can verify the source and version of the module that you are using?

**Comment by MichaelMackus** [comment]
Hmm. I'm using 5.0.0 of puppet-nodejs, commit SHA c77134280b7e30f3c8a94448e04de5c238e6c89c - looks like that's the latest commit according to Github.

**Comment by MichaelMackus** [comment]
OK that was weird! Looks like my puppet module inside the container was different than the one on my host (which is 5.0.0). I did a quick update of the module, and everything is working as expected now!

Sorry for the false alarm. In any case, glad this is figured out, was a huge annoyance.

**Comment by juniorsysadmin** [comment]
Something is not right here because
```
Notice: /Stage[main]/Nodejs::Install/File[/usr/bin/node]/ensure: ensure changed 'file' to 'link'
```
is from a section in nodejs::install that no longer exists in 5.0.0 on the Forge or on tagged 5.0.0
