### ISSUE TITLE
check fedora support

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-nodejs#371]
this module once listed fedora in the metadata.json. We removed it because all listed versions are EOL. We need to check if recent fedora versions work and add them back.

**Comment by juniorsysadmin** [comment]
Recent Fedora versions _should_ work, but continually adding/remove them to metadata.json will create too much unnecessary code churn, which we don't want to do. And we only want to add operating system values without a version for rolling distributions like ArchLinux.

The README lists Fedora as an operating system that is not tested but should work.
