### ISSUE TITLE
Expected value for repo_pin

### ISSUE THREAD

**Issue by gesinn-it** [voxpupuli/puppet-nodejs#382]
I want to install nodejs 6.x on Ubuntu Server 18.04 and run into the same issue as reported here:

https://askubuntu.com/questions/1086445/why-does-the-script-for-installing-nodejs-6-x-installs-8-10

"Why does the script for installing nodejs 6_x installs 8_10?"

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.x
- Distribution: Ubuntu Server 18.04
- Module version: 6.0.0

## How to reproduce (e.g Puppet code you use)
class { 'nodejs':
  nodejs_dev_package_ensure => 'present',
  npm_package_ensure        => 'present',
  repo_url_suffix => '6.x',
  repo_pin        => 10,
}

## What are you seeing
nodejs 8.x installed

## What behaviour did you expect instead
nodejs 6.x installed

## Any additional information you'd like to impart
I also tried to set

  repo_pin => '6.14.1-1nodesource1',

**Comment by juniorsysadmin** [comment]
@gesinn-it Within /etc/apt take a look at the default value of the pin for the official Ubuntu repositories - it's possible that they are set to a value much higher than 10.
Also see:
https://help.ubuntu.com/community/PinningHowto
