### ISSUE TITLE
apt and yum resources are not listed as dependencies

### ISSUE THREAD

**Issue by logicminds** [voxpupuli/puppet-nodejs#393]
Puppet 6 removed the apt resource from the core so it needs to be downloaded separately and listed as a dependency.  Without these dependencies this modules does not work.

Would likely have to also add yum_repo as a dependency too.

Once the apt resource is added install can continue. 

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6
- Ruby:
- Distribution: linux-mint
- Module version: 7.0.0

**Comment by juniorsysadmin** [comment]
apt and probably yum falls under the category of a soft dependency https://puppet.com/docs/puppet/6.0/style_guide.html#dependencies and I am strongly against adding them as a hard dependency as it causes all kinds of usability and maintenance issues longer term.

The README does mention puppetlabs-apt, but perhaps now with the removal of things from core, more needs to be listed there as part of a Pull Request.

**Comment by dhoppe** [comment]
@juniorsysadmin I agree that these modules should not be defined as hard dependency, but maybe we should add the following code to our modules, because not everyone reads the docs carefully:
```
if $facts['package_provider'] == 'deb' and !defined('apt') {
  fail('Please provide the module puppetlabs-apt')
} elsif $facts['package_provider'] == 'yum' and !defined('yumrepo_core') {
  fail('Please provide the module puppetlabs-yumrepo_core')
}
```

**Comment by dhoppe** [comment]
On second thought, I would love to see this at ```puppetlabs-stdlib```, because we would not need to change our modules. But I think the list of modules would be endless:
* puppetlabs-apt
* puppetlabs-mysql
* puppetlabs-postgresql
* puppetlabs-yumrepo_core
* camtocamp-systemd
* stahnma-epel
* ...

**Comment by juniorsysadmin** [comment]
#395
