### ISSUE TITLE
Add Debian 10 (Buster) support

### ISSUE THREAD

**Issue by xzavrel** [voxpupuli/puppet-nodejs#400]
Hi guys, as Debian Buster has been released it would be nice to have the support for this one also. Is there anything blocking the 

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.7.2
- Ruby: 2.5
- Distribution: Debian 10 (Buster)
- Module version: 

## How to reproduce (e.g Puppet code you use)
Use Puppet `class { 'nodejs': }` on Debian 10.

## What are you seeing
Error: /Package[node-red]: Provider npm is not functional on this host

## What behaviour did you expect instead
npm should be installed

**Comment by mryanb** [comment]
Similar issue here.

**Comment by Dan33l** [comment]
@xzavrel and @mryanb hi.
Can you propose a PR ? We will be happy to merge it.

**Comment by juniorsysadmin** [comment]
Closed by #406
