### ISSUE TITLE
Missing dependency on package resource that installs NPM when using the nodesource repository

### ISSUE THREAD

**Issue by wiebe** [voxpupuli/puppet-nodejs#404]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: all
- Module version: probably v0.8.0 and above

## How to reproduce (e.g Puppet code you use)
Try to set a global_config_entry before the nodejs/npm package is being installed. As an example:
```
nodejs::npm::global_config_entry { 'always-auth':
   ensure => 'present',
   value  => 'true',
}
```

## What are you seeing
The npm_config exec fails and the config is not set.

## What behaviour did you expect instead
For the resource to apply without errors.

## Output log
```
Error: /bin/sh: 1: /usr/bin/npm: not found
       
Error: /Nodejs::Npm::Global_config_entry[always-auth]/Exec[npm_config present always-auth]/returns: change from 'notrun' to ['0'] failed: /bin/sh: 1: /usr/bin/npm: not found
```

## Any additional information you'd like to impart
I implemented a simple fix, will make a pull request.

**Comment by juniorsysadmin** [comment]
Fixed by #405
